# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Independence Testing in Time-series Data # The title of the book. Will be placed in the left navbar.
author: Jaewon Chung, Ronak Mehta # The author of the book
copyright: "2023" # Copyright year to be placed in the footer
logo: ./images/nd_logo.png # A path to the book logo
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: mgcx.tex
    theme: howto

sphinx:
  config: # key-value pairs to directly over-ride the Sphinx configuration
    language: en
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # html_extra_path: ["docs"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/neurodata/mgcx
  path_to_book: mgcx
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ./images/mage.png
  comments:
    hypothesis: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

parse:
  myst_enable_extensions: #https://myst-parser.readthedocs.io/en/latest/sphinx/reference.html#sphinx-config-options
    - linkify # automatically identify “bare” web URLs and add hyperlinks
    - dollarmath
    - amsmath
  myst_nb_output_stderr:
    - "remove"
